### ISSUE TITLE
skipping over "GenderizeIoRb::Errors::NameNotFound:" while iterating through an array 

### ISSUE THREAD

**Issue by joshthedudeoflife** [kaspernj/genderize_io_rb#3]
I have an array of about 127 names, Im trying to iterate through all of them and print out the possible gender but when it gets to a name it doesnt recognize I get "GenderizeIoRb::Errors::NameNotFound: Name was not found on Genderize.io: " and stop the itertion Is there anyway instead print "Unknown" instead?

**Comment by kaspernj** [comment]
@joshthedudeoflife: Can you please supply the code you are using?

**Comment by joshthedudeoflife** [comment]
I figured it out, sorry.  It took a few hours and some frustration, you can close this ticket.

**Comment by kaspernj** [comment]
@joshthedudeoflife: Great :-) Feel free to open another issue, if you have any other problems with the library :-)
